const K={I:"ufb_stock_items",T:"ufb_stock_transactions"};
const S=[["Apple","Fruits","KG",10],["Banana","Fruits","KG",8],["Orange","Fruits","KG",10],["Papaya","Fruits","KG",5],["Pineapple","Fruits","KG",5],["Watermelon","Fruits","KG",10],["Muskmelon","Fruits","KG",5],["Grapes","Fruits","KG",5],["Pomegranate","Fruits","KG",5],["Carrot","Vegetables","KG",3],["Beetroot","Vegetables","KG",3],["Almond","Nuts","KG",2],["Cashew","Nuts","KG",2],["Plastic Bowl","Packaging","PIECE",100],["Plastic Lid","Packaging","PIECE",100],["Juice Bottle","Juice / Beverage","BOTTLE",50]];
const id=p=>`${p}-${Date.now()}-${Math.floor(Math.random()*1e5)}`, today=()=>new Date().toISOString().slice(0,10);
const items=()=>JSON.parse(localStorage.getItem(K.I)||"[]"), tx=()=>JSON.parse(localStorage.getItem(K.T)||"[]");
const saveI=x=>localStorage.setItem(K.I,JSON.stringify(x)),saveT=x=>localStorage.setItem(K.T,JSON.stringify(x));
const cur=x=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",minimumFractionDigits:2}).format(+x||0);
const num=x=>new Intl.NumberFormat("en-IN",{maximumFractionDigits:3}).format(+x||0);
const esc=x=>String(x??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
function init(){if(!items().length)saveI(S.map(x=>({id:id("ITEM"),name:x[0],category:x[1],unit:x[2],minimumStock:x[3],createdAt:new Date().toISOString()})))}
function item(i){return items().find(x=>x.id===i)}
function stock(i){let iq=0,iv=0,oq=0;tx().forEach(t=>{if(t.itemId!==i)return;if(t.type==="IN"){iq+=+t.quantity;iv+=+t.totalValue}else oq+=+t.quantity});let r=iq?iv/iq:0,q=Math.max(0,iq-oq);return{availableQuantity:q,averageRate:r,stockValue:q*r}}
function status(i){let s=stock(i.id);return s.availableQuantity<=0?["Out of Stock","status-out"]:s.availableQuantity<=+i.minimumStock?["Low Stock","status-low"]:["Available","status-available"]}
function toast(m,type="info"){let e=document.createElement("div");e.className=`toast ${type}`;e.textContent=m;document.querySelector("#toastContainer").append(e);setTimeout(()=>e.remove(),3500)}
function populate(){let o=items().sort((a,b)=>a.name.localeCompare(b.name)).map(i=>`<option value="${i.id}">${esc(i.name)} (${esc(i.unit)})</option>`).join("");["stockInItem","stockOutItem"].forEach(x=>{let e=document.getElementById(x),v=e.value;e.innerHTML=`<option value="">Select Item</option>${o}`;e.value=v})}
function dashboard(){let a=items(),t=tx(),d=today(),v=a.reduce((s,i)=>s+stock(i.id).stockValue,0);document.querySelector("#totalStockItems").textContent=a.length;document.querySelector("#todayStockInValue").textContent=cur(t.filter(x=>x.date===d&&x.type==="IN").reduce((s,x)=>s+ +x.totalValue,0));document.querySelector("#todayStockOutValue").textContent=cur(t.filter(x=>x.date===d&&x.type==="OUT").reduce((s,x)=>s+ +x.totalValue,0));document.querySelector("#currentStockValue").textContent=cur(v);stockTable()}
function stockTable(){let q=document.querySelector("#stockSearch").value.toLowerCase(),c=document.querySelector("#stockCategoryFilter").value,a=items().filter(i=>i.name.toLowerCase().includes(q)&&(!c||i.category===c));document.querySelector("#currentStockTable").innerHTML=a.length?a.sort((a,b)=>a.name.localeCompare(b.name)).map(i=>{let s=stock(i.id),z=status(i);return `<tr><td><b>${esc(i.name)}</b></td><td>${esc(i.category)}</td><td>${i.unit}</td><td>${num(s.availableQuantity)} ${i.unit}</td><td>${cur(s.averageRate)}/${i.unit}</td><td><b>${cur(s.stockValue)}</b></td><td><span class="status-badge ${z[1]}">${z[0]}</span></td></tr>`}).join(""):`<tr><td colspan="7" class="empty-state">No stock items found.</td></tr>`}
function inUnit(){let i=item(document.querySelector("#stockInItem").value);document.querySelector("#stockInUnit").value=i?.unit||"";inCalc()}
function inCalc(){let q=+document.querySelector("#stockInQuantity").value||0,r=+document.querySelector("#stockInRate").value||0;document.querySelector("#stockInTotal").value=cur(q*r)}
function outDetails(){let i=item(document.querySelector("#stockOutItem").value);if(!i){document.querySelector("#stockOutUnit").value="";document.querySelector("#stockOutRate").value="";document.querySelector("#availableStockInfo").textContent="Select an item to view available stock.";outCalc();return}let s=stock(i.id);document.querySelector("#stockOutUnit").value=i.unit;document.querySelector("#stockOutRate").value=`${cur(s.averageRate)}/${i.unit}`;document.querySelector("#availableStockInfo").innerHTML=`Available stock: <strong>${num(s.availableQuantity)} ${i.unit}</strong> | Average rate: <strong>${cur(s.averageRate)}/${i.unit}</strong>`;outCalc()}
function outCalc(){let i=item(document.querySelector("#stockOutItem").value),q=+document.querySelector("#stockOutQuantity").value||0;document.querySelector("#stockOutTotal").value=i?cur(q*stock(i.id).averageRate):""}
function addIn(e){e.preventDefault();let i=item(document.querySelector("#stockInItem").value),q=+document.querySelector("#stockInQuantity").value,r=+document.querySelector("#stockInRate").value;if(!i||q<=0||r<0)return toast("Please enter valid stock details.","error");let a=tx();a.push({id:id("TXN"),date:document.querySelector("#stockInDate").value,type:"IN",itemId:i.id,itemName:i.name,category:i.category,quantity:q,unit:i.unit,rate:r,totalValue:q*r,reason:"",supplier:document.querySelector("#stockInSupplier").value.trim(),reference:document.querySelector("#stockInReference").value.trim(),notes:document.querySelector("#stockInNotes").value.trim(),createdAt:new Date().toISOString()});saveT(a);e.target.reset();document.querySelector("#stockInDate").value=today();render();toast(`${i.name} stock added successfully.`,"success")}
function addOut(e){e.preventDefault();let i=item(document.querySelector("#stockOutItem").value),q=+document.querySelector("#stockOutQuantity").value;if(!i||q<=0)return toast("Please enter a valid stock out quantity.","error");let s=stock(i.id);if(q>s.availableQuantity)return toast(`Insufficient stock. Available quantity: ${num(s.availableQuantity)} ${i.unit}`,"error");let a=tx();a.push({id:id("TXN"),date:document.querySelector("#stockOutDate").value,type:"OUT",itemId:i.id,itemName:i.name,category:i.category,quantity:q,unit:i.unit,rate:s.averageRate,totalValue:q*s.averageRate,reason:document.querySelector("#stockOutReason").value,supplier:"",reference:document.querySelector("#stockOutReference").value.trim(),notes:document.querySelector("#stockOutNotes").value.trim(),createdAt:new Date().toISOString()});saveT(a);e.target.reset();document.querySelector("#stockOutDate").value=today();document.querySelector("#availableStockInfo").textContent="Select an item to view available stock.";render();toast(`${i.name} stock removed successfully.`,"success")}
let cb=null;function confirm(title,msg,f){document.querySelector("#confirmTitle").textContent=title;document.querySelector("#confirmMessage").textContent=msg;cb=f;document.querySelector("#confirmModal").classList.add("show")}
function history(type,target){let a=tx().filter(x=>x.type===type).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));document.querySelector(target).innerHTML=a.length?a.map(t=>`<tr><td>${t.date.split("-").reverse().join("-")}</td><td><b>${esc(t.itemName)}</b></td><td>${num(t.quantity)}</td><td>${t.unit}</td><td>${cur(t.rate)}</td><td><b>${cur(t.totalValue)}</b></td><td>${type==="IN"?esc(t.supplier||"-"):esc(t.reason||"-")}</td><td>${esc(t.reference||"-")}</td><td><button class="table-action-btn" onclick="delTx('${t.id}')">Delete</button></td></tr>`).join(""):`<tr><td colspan="9" class="empty-state">No ${type==="IN"?"stock in":"stock out"} transactions yet.</td></tr>`}
function delTx(x){confirm("Delete Transaction","Are you sure? Stock values will be recalculated automatically.",()=>{saveT(tx().filter(t=>t.id!==x));render();toast("Transaction deleted and stock recalculated.","success")})}
function addItem(e){e.preventDefault();let n=document.querySelector("#itemName").value.trim(),a=items();if(a.some(i=>i.name.toLowerCase()===n.toLowerCase()))return toast("An item with this name already exists.","error");a.push({id:id("ITEM"),name:n,category:document.querySelector("#itemCategory").value,unit:document.querySelector("#itemUnit").value,minimumStock:+document.querySelector("#itemMinimumStock").value,createdAt:new Date().toISOString()});saveI(a);e.target.reset();render();toast(`${n} added successfully.`,"success")}
function itemTable(){let q=document.querySelector("#itemSearch").value.toLowerCase(),a=items().filter(i=>i.name.toLowerCase().includes(q));document.querySelector("#itemsTable").innerHTML=a.length?a.map(i=>{let s=stock(i.id),z=status(i);return `<tr><td><b>${esc(i.name)}</b></td><td>${esc(i.category)}</td><td>${i.unit}</td><td>${num(s.availableQuantity)} ${i.unit}</td><td>${num(i.minimumStock)} ${i.unit}</td><td><span class="status-badge ${z[1]}">${z[0]}</span></td><td><button class="table-action-btn" onclick="delItem('${i.id}')">Delete</button></td></tr>`}).join(""):`<tr><td colspan="7" class="empty-state">No items found.</td></tr>`}
function delItem(x){let i=item(x);if(tx().some(t=>t.itemId===x))return toast("This item cannot be deleted because it has transaction history.","error");confirm("Delete Item",`Are you sure you want to delete "${i.name}"?`,()=>{saveI(items().filter(i=>i.id!==x));render();toast("Item deleted successfully.","success")})}
function exportCSV(){let h=["Date","Transaction Type","Item","Category","Unit","Quantity","Rate","Value","Reason","Supplier","Reference","Notes"],rows=tx().map(t=>[t.date,t.type==="IN"?"Stock In":"Stock Out",t.itemName,t.category,t.unit,t.quantity,t.rate,t.totalValue,t.reason,t.supplier,t.reference,t.notes]),csv=[h,...rows].map(r=>r.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(",")).join("\n"),u=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=u;a.download=`UFB_Stock_Report_${today()}.csv`;a.click();URL.revokeObjectURL(u);toast("Stock report exported successfully.","success")}
function render(){populate();dashboard();history("IN","#stockInHistory");history("OUT","#stockOutHistory");itemTable()}
document.addEventListener("DOMContentLoaded",()=>{init();document.querySelector("#stockInDate").value=today();document.querySelector("#stockOutDate").value=today();document.querySelector("#todayDisplay").textContent=new Intl.DateTimeFormat("en-IN",{weekday:"long",day:"2-digit",month:"short",year:"numeric"}).format(new Date());document.querySelectorAll(".nav-link").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav-link").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".page").forEach(x=>x.classList.remove("active-page"));b.classList.add("active");document.getElementById(b.dataset.page).classList.add("active-page");document.querySelector("#sidebar").classList.remove("open");render()});document.querySelector("#stockInForm").onsubmit=addIn;document.querySelector("#stockOutForm").onsubmit=addOut;document.querySelector("#itemForm").onsubmit=addItem;document.querySelector("#stockInItem").onchange=inUnit;document.querySelector("#stockInQuantity").oninput=inCalc;document.querySelector("#stockInRate").oninput=inCalc;document.querySelector("#stockOutItem").onchange=outDetails;document.querySelector("#stockOutQuantity").oninput=outCalc;document.querySelector("#stockSearch").oninput=stockTable;document.querySelector("#stockCategoryFilter").onchange=stockTable;document.querySelector("#itemSearch").oninput=itemTable;document.querySelector("#exportReportBtn").onclick=exportCSV;document.querySelector("#confirmCancel").onclick=()=>document.querySelector("#confirmModal").classList.remove("show");document.querySelector("#confirmProceed").onclick=()=>{if(cb)cb();cb=null;document.querySelector("#confirmModal").classList.remove("show")};document.querySelector("#mobileMenuBtn").onclick=()=>document.querySelector("#sidebar").classList.toggle("open");render()});