const KEY='masterExpenseManagementV1';
const defaultCategories=['Marketing','Meta Ads','Google Ads','Salary','Rent','Electricity','Internet','Software','Travel','Fuel','Vehicle Maintenance','Fruit Purchase','Vegetable Purchase','Packaging','Kitchen Materials','Construction Materials','Labour','Site Development','Printing','Lead Generation','Events','Office Expense','Food','Hospitality','Miscellaneous'];
const seed=[
{id:'EXP-001',date:'2026-08-03',company:'Urban Fruit Bowl',category:'Fruit Purchase',description:'Weekly fruit supplier payment',vendor:'Fresh Farm Supplier',amount:18500,paymentMode:'UPI',paidBy:'Operations Team',moneySource:'Company Account',status:'Approved',bill:'Yes',remarks:''},
{id:'EXP-002',date:'2026-08-05',company:'Western Mylands',category:'Meta Ads',description:'Property lead campaign',vendor:'Meta Ads',amount:25000,paymentMode:'Credit Card',paidBy:'Narender',moneySource:'Credit Card',status:'Approved',bill:'Yes',remarks:''},
{id:'EXP-003',date:'2026-08-10',company:'Urban Fruit Bowl',category:'Packaging',description:'Fruit bowl packaging material',vendor:'PackPro',amount:12400,paymentMode:'Bank Transfer',paidBy:'Balu Sir',moneySource:'Company Account',status:'Pending',bill:'No',remarks:''},
{id:'EXP-004',date:'2026-08-15',company:'Western Mylands',category:'Printing',description:'Project brochure printing',vendor:'Print House',amount:8200,paymentMode:'Cash',paidBy:'Office',moneySource:'Company Cash',status:'Approved',bill:'Yes',remarks:''},
{id:'EXP-005',date:'2026-07-20',company:'Urban Fruit Bowl',category:'Fuel',description:'Delivery vehicle fuel',vendor:'Fuel Station',amount:6500,paymentMode:'UPI',paidBy:'Delivery Team',moneySource:'Company Account',status:'Approved',bill:'No',remarks:''},
{id:'EXP-006',date:'2026-07-25',company:'Western Mylands',category:'Lead Generation',description:'Real estate lead service',vendor:'Lead Partner',amount:18000,paymentMode:'Bank Transfer',paidBy:'Balu Sir',moneySource:'Company Account',status:'Approved',bill:'Yes',remarks:''}
];
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{expenses:seed,categories:defaultCategories}}catch{return {expenses:seed,categories:defaultCategories}}}
let data=load(), range='all', customFrom='', customTo='';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function money(n){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n)||0)}
function dateText(d){return new Date(d+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function getFiltered(){let a=[...data.expenses], comp=$('#globalCompany').value; if(comp!=='All')a=a.filter(x=>x.company===comp); const now=new Date(), today=new Date(now.getFullYear(),now.getMonth(),now.getDate()); if(range==='today')a=a.filter(x=>x.date===today.toISOString().slice(0,10)); if(range==='week'){const start=new Date(today);start.setDate(today.getDate()-today.getDay());a=a.filter(x=>new Date(x.date+'T00:00:00')>=start&&new Date(x.date+'T00:00:00')<=now)} if(range==='month')a=a.filter(x=>{let d=new Date(x.date+'T00:00:00');return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()});if(range==='lastMonth'){let d0=new Date(now.getFullYear(),now.getMonth()-1,1),d1=new Date(now.getFullYear(),now.getMonth(),0);a=a.filter(x=>{let d=new Date(x.date+'T00:00:00');return d>=d0&&d<=d1})}if(customFrom)a=a.filter(x=>x.date>=customFrom);if(customTo)a=a.filter(x=>x.date<=customTo);return a}
function renderDashboard(){const a=getFiltered(), total=a.reduce((s,x)=>s+Number(x.amount),0),ufb=a.filter(x=>x.company==='Urban Fruit Bowl'),wm=a.filter(x=>x.company==='Western Mylands'),sum=z=>z.reduce((s,x)=>s+Number(x.amount),0),pending=a.filter(x=>x.status==='Pending');$('#totalExpense').textContent=money(total);$('#totalCount').textContent=`${a.length} transactions`;$('#ufbTotal').textContent=money(sum(ufb));$('#ufbCount').textContent=`${ufb.length} expenses`;$('#wmTotal').textContent=money(sum(wm));$('#wmCount').textContent=`${wm.length} expenses`;$('#pendingTotal').textContent=money(sum(pending));$('#pendingCount').textContent=`${pending.length} pending`;
const months={};a.forEach(x=>{let k=x.date.slice(0,7);months[k]=(months[k]||0)+Number(x.amount)});let keys=Object.keys(months).sort().slice(-6),max=Math.max(...keys.map(k=>months[k]),1);$('#monthlyChart').innerHTML=keys.length?keys.map(k=>`<div class="bar-wrap"><div class="bar-value">${money(months[k])}</div><div class="bar" style="height:${Math.max(4,months[k]/max*190)}px"></div><div class="bar-label">${new Date(k+'-01T00:00:00').toLocaleDateString('en',{month:'short'})}</div></div>`).join(''):'<p class="muted">No data for this period.</p>';
const cats={};a.forEach(x=>cats[x.category]=(cats[x.category]||0)+Number(x.amount));let catRows=Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,6);$('#categoryChart').innerHTML=catRows.length?catRows.map(([k,v])=>`<div class="category-row"><div class="category-top"><span>${esc(k)}</span><b>${money(v)}</b></div><div class="progress"><i style="width:${v/(catRows[0][1]||1)*100}%"></i></div></div>`).join(''):'<p class="muted">No category data.</p>';
$('#recentBody').innerHTML=a.sort((x,y)=>y.date.localeCompare(x.date)).slice(0,6).map(rowSmall).join('')||'<tr><td colspan="6" class="muted">No expenses yet.</td></tr>'}
function badge(s){return `<span class="badge ${s.toLowerCase()}">${s}</span>`}
function rowSmall(x){return `<tr><td>${dateText(x.date)}</td><td>${esc(x.company)}</td><td>${esc(x.category)}</td><td>${esc(x.description)}</td><td><b>${money(x.amount)}</b></td><td>${badge(x.status)}</td></tr>`}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function renderExpenses(){let a=getFiltered(),q=$('#searchExpenses').value.toLowerCase(),status=$('#statusFilter').value,cat=$('#categoryFilter').value;if(q)a=a.filter(x=>Object.values(x).join(' ').toLowerCase().includes(q));if(status!=='All')a=a.filter(x=>x.status===status);if(cat!=='All')a=a.filter(x=>x.category===cat);a.sort((x,y)=>y.date.localeCompare(x.date));$('#expensesBody').innerHTML=a.map(x=>`<tr><td>${dateText(x.date)}</td><td>${esc(x.company)}</td><td>${esc(x.category)}</td><td>${esc(x.description)}</td><td>${esc(x.vendor||'-')}</td><td>${esc(x.paidBy||'-')}</td><td><b>${money(x.amount)}</b></td><td>${badge(x.status)}</td><td><button class="action-btn" onclick="editExpense('${x.id}')">Edit</button><button class="action-btn delete" onclick="deleteExpense('${x.id}')">Delete</button></td></tr>`).join('');$('#emptyState').style.display=a.length?'none':'block'}
function renderCategoryOptions(){let opts=['<option value="">Select Category</option>',...data.categories.map(c=>`<option>${esc(c)}</option>`)];$('#category').innerHTML=opts.join('');$('#categoryFilter').innerHTML='<option value="All">All Categories</option>'+data.categories.map(c=>`<option>${esc(c)}</option>`).join('')}
function renderSettings(){$('#categoryList').innerHTML=data.categories.map((c,i)=>`<span class="tag">${esc(c)} <button onclick="removeCategory(${i})">×</button></span>`).join('')}
function renderReports(){let a=[...data.expenses],comp=$('#reportCompany').value,m=$('#reportMonth').value;if(comp!=='All')a=a.filter(x=>x.company===comp);if(m)a=a.filter(x=>x.date.startsWith(m));let total=a.reduce((s,x)=>s+Number(x.amount),0);$('#reportTotal').textContent=money(total);$('#reportTransactions').textContent=a.length;$('#reportAverage').textContent=money(a.length?total/a.length:0);const build=(obj)=>Object.entries(obj).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="summary-row"><div class="summary-top"><span>${esc(k)}</span><b>${money(v)}</b></div></div>`).join('')||'<p class="muted">No data.</p>';let cats={},pays={},companies={};a.forEach(x=>{cats[x.category]=(cats[x.category]||0)+Number(x.amount);pays[x.paymentMode]=(pays[x.paymentMode]||0)+Number(x.amount);companies[x.company]=(companies[x.company]||0)+Number(x.amount)});$('#reportCategories').innerHTML=build(cats);$('#reportPayments').innerHTML=build(pays);$('#companyComparison').innerHTML=build(companies)}
function renderAll(){renderCategoryOptions();renderDashboard();renderExpenses();renderSettings();renderReports()}
function openModal(id){$('#modal').classList.remove('hidden');$('#expenseForm').reset();$('#date').value=new Date().toISOString().slice(0,10);$('#editId').value='';$('#modalTitle').textContent='Add Expense';if(id){let x=data.expenses.find(e=>e.id===id);if(!x)return;$('#modalTitle').textContent='Edit Expense';for(let k of ['date','company','category','amount','description','vendor','paymentMode','paidBy','moneySource','status','bill','remarks'])$('#'+k).value=x[k]??'';$('#editId').value=id}}
function closeModal(){$('#modal').classList.add('hidden')}
window.editExpense=id=>openModal(id);window.deleteExpense=id=>{if(confirm('Delete this expense?')){data.expenses=data.expenses.filter(x=>x.id!==id);save();renderAll();toast('Expense deleted')}}
window.removeCategory=i=>{if(confirm('Remove this category?')){data.categories.splice(i,1);save();renderAll()}}
$('#expenseForm').addEventListener('submit',e=>{e.preventDefault();let id=$('#editId').value;let obj={id:id||('EXP-'+Date.now().toString().slice(-7)),date:$('#date').value,company:$('#company').value,category:$('#category').value,amount:Number($('#amount').value),description:$('#description').value.trim(),vendor:$('#vendor').value.trim(),paymentMode:$('#paymentMode').value,paidBy:$('#paidBy').value.trim(),moneySource:$('#moneySource').value,status:$('#status').value,bill:$('#bill').value,remarks:$('#remarks').value.trim()};if(id){let i=data.expenses.findIndex(x=>x.id===id);data.expenses[i]=obj;toast('Expense updated')}else{data.expenses.push(obj);toast('Expense saved')}save();closeModal();renderAll()});
$('#addExpenseBtn').onclick=()=>openModal();$('#closeModal').onclick=closeModal;$('#cancelModal').onclick=closeModal;
$$('.nav').forEach(b=>b.onclick=()=>{let v=b.dataset.view;$$('.nav').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$('#pageTitle').textContent=b.innerText.trim();$('.sidebar').classList.remove('open');if(v==='reports')renderReports()});
$$('[data-go]').forEach(b=>b.onclick=()=>document.querySelector(`[data-view="${b.dataset.go}"]`).click());
$('#globalCompany').onchange=()=>{renderDashboard();renderExpenses()};
$('#quickFilters').onclick=e=>{if(e.target.dataset.range){range=e.target.dataset.range;customFrom=customTo='';$('#fromDate').value=$('#toDate').value='';$$('.chip').forEach(x=>x.classList.toggle('active',x===e.target));renderDashboard();renderExpenses()}};
$('#applyDates').onclick=()=>{range='all';customFrom=$('#fromDate').value;customTo=$('#toDate').value;$$('.chip').forEach(x=>x.classList.remove('active'));renderDashboard();renderExpenses()};
['searchExpenses','statusFilter','categoryFilter'].forEach(id=>$('#'+id).addEventListener('input',renderExpenses));$('#clearFilters').onclick=()=>{$('#searchExpenses').value='';$('#statusFilter').value='All';$('#categoryFilter').value='All';renderExpenses()};
$('#addCategory').onclick=()=>{let c=$('#newCategory').value.trim();if(c&&!data.categories.includes(c)){data.categories.push(c);$('#newCategory').value='';save();renderAll();toast('Category added')}};
$('#reportCompany').onchange=renderReports;$('#reportMonth').onchange=renderReports;$('#printReport').onclick=()=>window.print();
$('#exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='expense-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href);toast('Backup exported')};
$('#importFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);if(!Array.isArray(d.expenses)||!Array.isArray(d.categories))throw 0;data=d;save();renderAll();toast('Backup imported')}catch{alert('Invalid backup file')}};r.readAsText(f)};
$('#resetBtn').onclick=()=>{if(confirm('Reset all data to demo data?')){data={expenses:seed,categories:defaultCategories};save();renderAll();toast('Demo data restored')}};
$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');
$('#todayText').textContent=new Date().toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
$('#reportMonth').value=new Date().toISOString().slice(0,7);renderAll();
